### PR TITLE
Add install target and integration tests

### PR DESCRIPTION
**Pull request by aqnuep**
This solution is far from perfect, as the project lacks a proper directory structure, but at least allows for using the repository as a dependency in ecosystem components.

If preferred, we can rework the directory structure too.

### CODE REVIEW

**Comment by aqnuep** [comment]
I spoke too soon, I just realized that this code depends on the `vulkan_sc_core.hpp`, i.e. the C++ header, which is quite unfortunate, because it makes it incompatible with the ecosystem components in general, which do not generate combined C++ headers of any sort.

**Comment by dgkoch** [comment]
> I spoke too soon, I just realized that this code depends on the `vulkan_sc_core.hpp`, i.e. the C++ header, which is quite unfortunate, because it makes it incompatible with the ecosystem components in general, which do not generate combined C++ headers of any sort.

Does it really though?  All it really needs is what's defined in `fake/vulkan/vulkan_sc_core.hpp` which is just the pipeline cache structures, which should be the same as those in the C header.

**Comment by aqnuep** [comment]
I guess where I'm trying to get to is that probably we should do some more intrusive changes and put together something more robust, one of them being the chamge to the used includes, but sure, you're right.

**Comment by dgkoch** [comment]
I don't mind if you want to do it more robustly.  I made the fake header thing long before we had the VulkanSC-Headers repo that we could pull in easily.

**Comment by aqnuep** [comment]
Closing this MR for now, we will figure out the long-term plan for this first.

**Pull request closed without merging**
